name: GitHub Actions Demo create s3

on:
   push:
      branches: [ main ]
   pull_request:
      branches: [ main ]

jobs:
   build:
      runs-on: ubuntu-latest

steps:
     - uses: actions/checkout@master
- name: Upload to S3
     run: |
        aws s3 mb s3://romulo-amaral-github-actions
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'