name: GitHub Actions Demo model deploy

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::276848361358:role/sagemaker-role-demo
          aws-region: eu-west-1

      - name: Check if login
        run: aws sts get-caller-identity